import {
  ArrowLeft, Send, Settings, BookOpen, Brain, Sparkles, FileText, Video,
  FileSpreadsheet, Plus, Upload, Link, GripVertical, X, Check, Zap, FileEdit,
  Activity, Pencil, Save, Target, Lightbulb, MessageCircle, Clock, FolderOpen,
  ListChecks, ChevronRight, ChevronLeft, Play, Download, Eye, Search, BarChart3, Map,
  CheckCircle2, Circle, Bot, MessageSquare, Pause, RotateCcw, GitBranch,
  Edit, Image as ImageIcon, Mic, Trash2, Layers, Award, TrendingUp,
  ChevronDown, ChevronUp, Layout, Share2, AlertCircle, Globe, Database,
  Workflow, TestTube2, CreditCard, Film, Presentation,
} from 'lucide-react';

// Helper function to get icon component from icon name
export function getIconComponent(iconName: string) {
  const iconMap: Record<string, any> = {
    'FileEdit': FileEdit,
    'TestTube2': TestTube2,
    'Presentation': Presentation,
    'Film': Film,
    'CreditCard': CreditCard,
    'Workflow': Workflow,
    'Database': Database,
    'Globe': Globe,
    'AlertCircle': AlertCircle,
    'Share2': Share2,
    'Layout': Layout,
    'ChevronUp': ChevronUp,
    'ChevronDown': ChevronDown,
    'TrendingUp': TrendingUp,
    'Award': Award,
    'Layers': Layers,
    'Trash2': Trash2,
    'Mic': Mic,
    'ImageIcon': ImageIcon,
    'Edit': Edit,
    'GitBranch': GitBranch,
    'RotateCcw': RotateCcw,
    'Pause': Pause,
    'MessageSquare': MessageSquare,
    'Bot': Bot,
    'Circle': Circle,
    'CheckCircle2': CheckCircle2,
    'Map': Map,
    'BarChart3': BarChart3,
    'Search': Search,
    'Eye': Eye,
    'Download': Download,
    'Play': Play,
    'ChevronLeft': ChevronLeft,
    'ChevronRight': ChevronRight,
    'ListChecks': ListChecks,
    'FolderOpen': FolderOpen,
    'Clock': Clock,
    'MessageCircle': MessageCircle,
    'Lightbulb': Lightbulb,
    'Target': Target,
    'Save': Save,
    'Pencil': Pencil,
    'Activity': Activity,
    'Zap': Zap,
    'Check': Check,
    'X': X,
    'GripVertical': GripVertical,
    'Link': Link,
    'Upload': Upload,
    'Plus': Plus,
    'FileSpreadsheet': FileSpreadsheet,
    'Video': Video,
    'FileText': FileText,
    'Sparkles': Sparkles,
    'Brain': Brain,
    'BookOpen': BookOpen,
    'Settings': Settings,
    'Send': Send,
    'ArrowLeft': ArrowLeft,
  };
  return iconMap[iconName] || AlertCircle;
}
